site_name: Arachne Web Framework
theme: readthedocs
extra_javascript:
    - underscore-min.js
    - versions.js
extra_css:
    - api-override.css
    - extra.css
site_url: http://docs.arachne-framework.org
repo_url: https://github.com/arachne-framework/arachne-docs
site_description: 'Documentation for the Arachne Web Framework'
copyright: '© Luke VanderHart 2017'
pages:
    - Home: index.md
    - Versions: versions.md
    - Architectural Overview: architecture.md
    - Tutorials:
        - 'Creating a Project': tutorials/creating-a-project.md
        - 'Handling HTTP Requests': tutorials/http-requests.md
        - 'Dependency Injection': tutorials/dependency-injection.md
        - 'Request Interceptors': tutorials/interceptors.md
        - 'Static Assets': tutorials/serving-assets.md
        - 'ClojureScript': tutorials/cljs.md
        - 'Figwheel': tutorials/figwheel.md
    - Modules:
        - 'arachne-core': 'modules/arachne-core.md'
        - 'arachne-http': 'modules/arachne-http.md'
        - 'arachne-pedestal': 'modules/arachne-pedestal.md'
        - 'arachne-assets': 'modules/arachne-assets.md'
        - 'arachne-cljs': 'modules/arachne-cljs.md'
        - 'arachne-figwheel': 'modules/arachne-figwheel.md'
    - Contributing: contributing.md
    - API Documentation: api/index.md

